version: "3.8"
services:
  web:
    build: .
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo
    restart: unless-stopped
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
volumes:
  mongo-data:
