version: "3.8"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SOCKET_URL=http://10.4.56.60:4000 # Updated to use service name
    depends_on:
      - mongo
      - api
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", 'mongo --eval "db.adminCommand(\"ping\")" || exit 1']
      interval: 30s
      timeout: 10s
      retries: 5
volumes:
  mongo-data:
