version: "3.8"
services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/mydatabase
      - NEXT_PUBLIC_SOCKET_URL=http://10.4.56.60:80
    depends_on:
      - mongo
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", 'mongo --eval ''db.adminCommand("ping")'' || exit 1']
      interval: 30s
      timeout: 10s
      retries: 5
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    
  vpn:
    image: hwdsl2/ipsec-vpn-server
    environment:
      - VPN_IPSEC_PSK=K4rW9nKp0XtZyL4ZX5g7E5fP7aN3M8t6o4F2Q3iA7eC0B8uR6h9A5d0F3G7L8p1Z
      - VPN_USER=username
      - VPN_PASSWORD=password
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    restart: unless-stopped
volumes:
  mongo-data:
