version: "3.8"
services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/mydatabase
      - NEXT_PUBLIC_SOCKET_URL=http://10.4.56.60:80
    depends_on:
      - mongo
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", 'mongo --eval ''db.adminCommand("ping")'' || exit 1']
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mongo-data:
