version: "3.8"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/mydatabase
      - NEXT_PUBLIC_SOCKET_URL=http://web:3000 # Updated to use service name
    depends_on:
      - mongo
      - vpn
    networks:
      - vpn_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - vpn_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", 'mongo --eval "db.adminCommand(\"ping\")" || exit 1']
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - vpn_network
    restart: unless-stopped

networks:
  vpn_network:
    external: true

volumes:
  mongo-data:
