import type { Metadata } from "next";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import { AppProvider } from "../context/AppContext";

import "@/styles/index.scss";
import "@/styles/globals.css";
import { ModalProvider } from "../context/ModalContext";
import ModalWrapper from "@/components/modals/modal.wrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>
          <ModalProvider>
            {children}
            <ModalWrapper />
          </ModalProvider>
        </AppProvider>
      </body>
    </html>
  );
}
